spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: host_route1 # 指定路由唯一标识
          uri: lb://service1 #需要转发的地址，lb指的是从nacos中按照名称获取微服务,并遵循负载均衡策略
          predicates:
            - Path=/gateway/service1/** # - Path 基于路径的断言
            - Before=2022-08-09T19:45:00.000+08:00[Asia/Shanghai] # 指定时间访问  类似的还有 After、Between（用逗号隔开）
            - Cookie=username,tyc # 必须cookie种携带 username=tyc 也可以输入正则表达式
          filters:
            - StripPrefix=2  # 跳过前缀 即拦截 /gateway/service1/ 开头的请求 去掉 /gateway/service1 转发到目标服务地址


server:
  port: 8088
